'use strict'
/**
 * Design tokens: single source for Tailwind and CSS.
 * CSS vars are generated by scripts/generate-theme-css.js → styles/_theme-vars.css
 */
const colors = {
  cta: '#D6A269',
}

/** Mauve scale: 12 steps */
const mauve = {
  1: '#fdfcfd',
  2: '#faf9fb',
  3: '#f6f4f8',
  4: '#f0eef3',
  5: '#eae7ed',
  6: '#e3dfe6',
  7: '#ddd8e0',
  8: '#d2cdd7',
  9: '#c4bfc9',
  10: '#a8a3ae',
  11: '#6e6a75',
  12: '#2d2b30',
}

/** Dark mauve scale: same hue, darker range */
const mauveDark = {
  1: '#1c1b1f',
  2: '#232225',
  3: '#2a282d',
  4: '#312f34',
  5: '#38363c',
  6: '#403d44',
  7: '#48454c',
  8: '#504d55',
  9: '#5f5c66',
  10: '#8b8792',
  11: '#b5b0bc',
  12: '#e6e1e9',
}

const light = {
  1: mauve[1],
  2: mauve[2],
  3: mauve[3],
  4: mauve[6],
  5: mauve[11],
  6: mauve[12],
}

const dark = {
  1: mauveDark[1],
  2: mauveDark[2],
  3: mauveDark[3],
  4: mauveDark[10],
  5: mauveDark[11],
  6: mauveDark[12],
}

module.exports = {
  colors,
  mauve,
  mauveDark,
  light,
  dark,
}
